AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for ECS task's Project cq_dev_x
Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cq_dev_xTaskRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: cq_dev_xlogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:logs:us-east-2:502937263541:log-group:cq_dev_x:*
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: cq_dev_xCredentials
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:secretsmanager:us-east-2:502937263541:secret:cq_dev_x-*
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
Outputs:
  TaskRoleArn:
    Value: !Ref TaskRole
    Description: ARN of Task Role
